name: HunterHardcore
version: 1.1
main: org.mystuff.HunterHardcorePlugin
api-version: 1.21.1
commands:
  starthunt:
    description: Start the hunter game
    usage: /starthunt
  stophunt:
    description: Stop the hunter game
    usage: /stophunt
  stophunt:
    description: Tracks the nearest player
    usage: /tracknearest