name: mc-manhunt
version: 1.3.6
main: org.mystuff.McManhunt
api-version: 1.21.1
commands:
  starthunt:
    description: Start the hunter game
    usage: /starthunt
  stophunt:
    description: Stop the hunter game
    usage: /stophunt
  tracknearest:
    description: Tracks the nearest player
    usage: /tracknearest
  accuse:
    description: Accuse a player of being a hunter
    usage: /accuse <playerName>